#! /bin/bash
note_name=$1
note_path=Notes/$note_name

#Creating new document and folder
mkdir -p ./$note_path
mkdir -p ./$note_path/img
touch ./$note_path/$note_name.md
echo `pwd`/$note_path > ~/pwd

#Some configuration for convenient
pushd ./$note_path > /dev/null
save_current_pwd
open .
popd  > /dev/null


echo "created new note @ `pwd`/$note_path"


